{
 "title": "EPPDemo",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Throughput per sec",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Throughput - Higher is Better",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 18, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{job=\"primes.oraclejdk8\", status=\"200\", uri=\"/primes\"}[$__interval])",
     "legendFormat": "Throughput / JDK8"
    },
    {
     "expr": "rate(http_server_requests_seconds_count{job=\"primes.oraclejdkperf\", status=\"200\", uri=\"/primes\"}[$__interval])",
     "legendFormat": "Throughput / JDKPerf"
    }
   ]
  },
  {
   "title": "Throughput Improvement",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(rate(http_server_requests_seconds_count{job=\"primes.oraclejdkperf\", status=\"200\", uri=\"/primes\"}[$__interval])) - sum(rate(http_server_requests_seconds_count{job=\"primes.oraclejdk8\", status=\"200\", uri=\"/primes\"}[$__interval]))) / sum(rate(http_server_requests_seconds_count{job=\"primes.oraclejdk8\", status=\"200\", uri=\"/primes\"}[$__interval])) * 100"
    }
   ]
  },
  {
   "title": "Average Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Average latency - Lower is Better",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 18, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate( http_server_requests_seconds_sum{job=\"primes.oraclejdk8\", status=\"200\", uri=\"/primes\"}[$__interval]) / rate( http_server_requests_seconds_count{job=\"primes.oraclejdk8\", status=\"200\", uri=\"/primes\"}[$__interval])",
     "legendFormat": "Request Average Duration / JDK8"
    },
    {
     "expr": "rate( http_server_requests_seconds_sum{job=\"primes.oraclejdkperf\", status=\"200\", uri=\"/primes\"}[$__interval]) / rate( http_server_requests_seconds_count{job=\"primes.oraclejdkperf\", status=\"200\", uri=\"/primes\"}[$__interval])",
     "legendFormat": "Request Average Duration / JDKPerf"
    }
   ]
  },
  {
   "title": "Latency Improvement",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(rate( http_server_requests_seconds_sum{job=\"primes.oraclejdk8\", status=\"200\", uri=\"/primes\"}[$__interval]) / rate( http_server_requests_seconds_count{job=\"primes.oraclejdk8\", status=\"200\", uri=\"/primes\"}[$__interval]))-sum(rate( http_server_requests_seconds_sum{job=\"primes.oraclejdkperf\", status=\"200\", uri=\"/primes\"}[$__interval]) / rate( http_server_requests_seconds_count{job=\"primes.oraclejdkperf\", status=\"200\", uri=\"/primes\"}[$__interval]))) / sum (rate( http_server_requests_seconds_sum{job=\"primes.oraclejdk8\", status=\"200\", uri=\"/primes\"}[$__interval]) / rate( http_server_requests_seconds_count{job=\"primes.oraclejdk8\", status=\"200\", uri=\"/primes\"}[$__interval])) * 100"
    }
   ]
  },
  {
   "title": "Application Throughput",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Throughput - Higher is Better ( JDK8 vs JDKPerf )",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{job=\"primes.oraclejdk8\", status=\"200\", uri=\"/primes\"}[$__interval])",
     "legendFormat": "OracleJDK8 (req / s)"
    },
    {
     "expr": "rate(http_server_requests_seconds_count{job=\"primes.oraclejdkperf\", status=\"200\", uri=\"/primes\"}[$__interval])",
     "legendFormat": "OracleJDKPerf (req / s)"
    }
   ]
  }
 ]
}